#!/bin/bash

DEHYDRATED_DIR="${DEHYDRATED_DIR:-/home/admin/dehydrated}"
LETSENCRYPT_DIR="${LETSENCRYPT_DIR:-/etc/ssl/letsetncrypt}"


if [[ "$UID" != 0 ]] ; then
    echo "must be root" >&2
    exit 2
fi

create_nginx_cert_sections() {

    mkdir -p /etc/nginx/includes/ssl-certs

    for site in "$LETSENCRYPT_DIR/"* ; do
        cat > "/etc/nginx/includes/ssl-certs/$(basename "$site")" <<EOF
ssl_certificate $site/fullchain.pem;
ssl_certificate_key $site/privkey.pem;
EOF
    done

}

copy_certs() {
    [[ -d "$DEHYDRATED_DIR"/certs/ ]] || return 1;
    for site in "$DEHYDRATED_DIR"/certs/*; do
        local dir="$LETSENCRYPT_DIR/$(basename "$site")"
        mkdir -p "$dir"
        chmod 0700 "$dir" &&
            cp -t "$dir" "$site"/{fullchain.pem,privkey.pem}  &&
            chmod 0600 "$site"/{fullchain.pem,privkey.pem}
    done &&
        maybe_copy_prosody_certs
}

maybe_copy_prosody_certs() {
    if systemctl is-active --quiet prosody ; then
        install -b -o prosody -g prosody -m 0600 "$LETSENCRYPT_DIR/read.now.im/fullchain.pem" /etc/prosody/certs/fullchain.pem &&
        install -b -o prosody -g prosody -m 0600 "$LETSENCRYPT_DIR/read.now.im/privkey.pem" /etc/prosody/certs/privkey.pem
    else
        return 0
    fi
}

reload_services() {
    for service in nginx dovecot postfix ; do
        systemctl is-active --quiet $service && systemctl reload $service
    done
    systemctl is-active --quiet prosody && systemctl restart prosody
    return 0
}

copy_certs &&
    create_nginx_cert_sections &&
    reload_services
