- block:

  - name: fetch repository
    git:
      repo: 'https://github.com/lukas2511/dehydrated.git'
      dest: /home/{{ adminuser }}/dehydrated/
      version: v0.6.5

  - name: domains.txt
    copy:
      content: "{{ ssl_domains }}"
      dest: /home/{{ adminuser }}/dehydrated/domains.txt
      owner: "{{ adminuser }}"
      group: "{{ admingroup }}"
      mode: 0644

  - name: config
    copy:
      content: |
        WELLKNOWN="/srv/http/letsencrypt"
      dest: /home/{{ adminuser }}/dehydrated/config
      owner: "{{ adminuser }}"
      group: "{{ admingroup }}"
      mode: 0644

  - name: letsencrypt challenge directory
    file:
      dest: /srv/http/letsencrypt
      state: directory
      owner: "{{ adminuser }}"
      group: "{{ admingroup }}"
      mode: 0755
    become_user: root

  - name: copy installcertkeys script
    copy:
      src: scripts/installcertkeys
      dest: /home/{{ adminuser }}/bin/installcertkeys
      owner: "{{ adminuser }}"
      group: "{{ admingroup }}"
      mode: 0700

  - name: certificates update cron job
    cron:
      name: certificates update
      hour: "19"
      minute: "45"
      day: "13,27"
      job: "/home/{{ adminuser }}/dehydrated/dehydrated -c"
      user: "{{ adminuser }}"

  - name: set dehydrated dir env var in crontab
    cron:
      env: yes
      name: DEHYDRATED_DIR
      value: "/home/{{ adminuser }}/dehydrated"
      user: root
      state: present
    become_user: root

  - name: certificates installation cron job
    cron:
      name: certificates installation
      hour: "19"
      minute: "46"
      day: "13,27"
      job: "/home/{{ adminuser }}/bin/installcertkeys"
      user: root
    become_user: root

  - name: maybe register letsencrypt account
    shell: '[[ -d accounts ]] || ./dehydrated --register --accept-terms'
    args:
      chdir: /home/{{ adminuser }}/dehydrated/
      executable: /bin/bash

  - name: update new certificates if any
    shell: ./dehydrated -c
    args:
      chdir: /home/{{ adminuser }}/dehydrated/

  - name: install certificates
    shell: /home/{{ adminuser }}/bin/installcertkeys
    environment:
      DEHYDRATED_DIR: "/home/{{ adminuser }}/dehydrated"
    become_user: root

  become: yes
  become_user: "{{ adminuser }}"
  tags:
    - dehydrated
