- name: install packages
  apt:
    name:
    - python3
    - python3-pip
    - python3-virtualenv
    - nginx
    - ntp
    - supervisor
    - uwsgi
    - uwsgi-plugin-python
    - uwsgi-plugin-python3
    state: present
  when: ansible_os_family|lower == 'debian'

- name: install packages
  pacman:
    name:
    - python
    - python-pip
    - python-virtualenv
    - nginx
    - ntp
    - supervisor
    - uwsgi
    - uwsgi-plugin-python2
    - uwsgi-plugin-python
    state: present
    update_cache: yes
    upgrade: yes
  when: ansible_os_family|lower == 'archlinux'
