- name: reload iptables
  shell: netfilter-persistent reload

- name: reload headers
  supervisorctl:
    name: headers
    state: restarted

- name: reload headers
  supervisorctl:
    name: headers
    state: restarted

- name: reload maildir-feed
  supervisorctl:
    name: maildir-feed
    state: restarted

- name: reload social-rss
  supervisorctl:
    name: social-rss
    state: restarted

- name: reload transfer.sh
  supervisorctl:
    name: transfer.sh
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload nsd
  service:
    name: nsd
    state: reloaded

- name: reload dovecot
  service:
    name: dovecot
    state: reloaded

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: update aliases
  shell: postalias /etc/aliases

- name: reload rspamd
  service:
    name: rspamd
    state: reloaded

- name: reload uwsgi
  service:
    name: uwsgi
    state: reloaded

- name: reload prosody
  service:
    name: prosody
    state: reloaded
