- name: reload iptables
  shell: netfilter-persistent reload

- name: reload supervisor
  supervisorctl:
    name: headers
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload nsd
  service:
    name: nsd
    state: reloaded

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: update aliases
  shell: postalias /etc/aliases
