- hosts: prod
  gather_facts: no
  become: yes

  tasks:

  - name: acme location
    copy:
      content: |
        location /.well-known/acme-challenge {
            alias /srv/http/letsencrypt;
        }
      dest: /etc/nginx/includes/acme-challenge
      owner: root
      group: root
      mode: 0644

  - name: acme configuraiton
    copy:
      src: etc/nginx/sites-available/acme
      dest: /etc/nginx/sites-available/acme
      owner: root
      group: root
      mode: 0644
    notify: reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
