- block:

  - name: install iptables packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - iptables
      - iptables-persistent
      - netfilter-persistent

  - name: iptables rules
    copy:
      src: etc/iptables/rules.v4
      dest: /etc/iptables/rules.v4
      owner: root
      group: root
      mode: 0640
    notify: reload iptables
