- block:

  - name: add maildir-feed user
    user: name=maildir-feed uid=1004 group=vmail append=yes home=/home/maildir-feed shell=/bin/false

  - name: install maildir-feed
    shell: go get "{{item}}"
    args:
      chdir: /home/maildir-feed
    environment:
      GOPATH: /home/maildir-feed
    with_items:
      - github.com/sloonz/maildir-feed/maildir-feed-rss
      - github.com/sloonz/maildir-feed/maildir-feed

  - name: /home/maildirs/feeds directory
    file:
      state: directory
      path: "{{ item }}"
      owner: vmail
      group: vmail
      mode: 0770
    with_items:
      - /home/maildirs
      - /home/maildirs/feeds

  - name: maildir-feed supervisor config
    copy:
      content: |
        [program:maildir-feed]
        command=/home/maildir-feed/bin/maildir-feed /home/maildirs/feeds/maildir | logger -t maildir-feed
        directory=/home/maildir-feed
        user=vmail
        group=vmail
        umask=007
        environment=HOME=/home/maildir-feed
      dest: /etc/supervisor/conf.d/maildir-feed.conf
      owner: root
      group: root
      mode: 0644
    notify: reload maildir-feed

  become: yes
  tags: [maildir-feed, feed]
